---
title: "Data Reformatting"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, message = FALSE}
library(dplyr)
library(tidyr)

# to call stats filter - stats::filter()
```


# Reformat Catch Data

* remove "all" column
* create species column
    - move from wide to long
* general QA

[Mike Byerly. Alaska commercial salmon catches by management region (1886- 1997). Gulf of Alaska Data Portal. df35b.304.2.](https://knb.ecoinformatics.org/view/df35b.304.2)

```{r}
catch_original <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"),
                    stringsAsFactors = FALSE)

head(catch_original)
```

Remove the `all` and `notesRegCode` columns using `select`
Cmd + shift + m : pipe operator shortcut %>% 

```{r}
catch_long <- catch_original %>% 
    select(-All, -notesRegCode) %>% # select columns we want
    gather(key = species, value = catch, #move from wide to long
           -Region, -Year)

head(catch_long)
```

```{r}
catch_wide <- catch_long %>% 
    spread(key = Region, value = catch)

head(catch_wide)
```


# Join the Region Definitions

# Misc. Functions
